workflows:
  flutter-ios-workflow:
    name: Flutter iOS Workflow
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.cocoapods/repos
        - ios/Pods